/**
 * Generate the default `.waffle/` overview docs from the computed render selection:
 *
 *   .waffle/CHEATSHEET.md   one-line cheat sheet of user-invocable skills (slash commands)
 *   .waffle/cheatsheet.svg  branded, self-contained visual of the same
 *   .waffle/TEAM.md         one-page introduction to the installed agents
 *   .waffle/team.svg        branded, self-contained visual of the same
 *
 * These are emitted through render's `emit()` choke point, so they are lock-tracked,
 * `doctor`-drift-checked, pruned when a later render no longer produces them, and refreshed
 * on every render — the "updated when necessary" behaviour falls out of the render lifecycle.
 *
 * The Markdown is the agent-readable source of truth (plain, scannable body). The SVGs are
 * the visual one-pagers — branded chrome only (per `assets/README.md`: waffle glyph +
 * Golden/Syrup/Cocoa palette in the header, plain body). Both are assembled purely from item
 * frontmatter (skills: `user-invocable` / `argument-hint` / `description`; agents: `name` /
 * `description` / `skills`), substituted with the same resolver render uses, so a
 * `{{project.name}}` in a description reads the same as in the rendered item.
 */
import fs from 'node:fs';
import path from 'node:path';
import { parseFrontmatter } from './util.mjs';
import { substitute } from './template.mjs';
import { makeResolver } from './project.mjs';

const CHEATSHEET_MD = path.join('.waffle', 'CHEATSHEET.md');
const CHEATSHEET_SVG = path.join('.waffle', 'cheatsheet.svg');
const TEAM_MD = path.join('.waffle', 'TEAM.md');
const TEAM_SVG = path.join('.waffle', 'team.svg');

// Description substitution never enforces `pattern:` guards (those police config values
// spliced into structured contexts, not prose) — pass an empty map.
const NO_PATTERNS = new Map();

/**
 * A skill is a slash command unless it explicitly opts out with `user-invocable: false`.
 * An absent key defaults to invocable — matching harness behaviour, so a skill that only
 * sets `disable-model-invocation: true` (e.g. `audit`) still shows on the cheat sheet.
 */
function isUserInvocable(data) {
  return data['user-invocable'] !== false;
}

/**
 * Build the doc payloads for the current selection. Returns `[{ rel, content }]` — the
 * caller emits each. A doc pair is omitted when its set is empty (no user-invocable skills
 * → no cheat sheet; no agents → no team page), so it prunes cleanly if a later selection
 * drops every item of that kind. Substitution problems (should not occur on a validated
 * toolkit, since descriptions are policed by `validate`) are pushed onto `errors`.
 */
export function generateWaffleDocs({ toolkit, project, selection, errors = [] }) {
  const primaryTarget = project.targets[0] ?? 'claude';
  const resolvers = new Map();
  const resolverFor = (stack) => {
    if (!resolvers.has(stack.name)) resolvers.set(stack.name, makeResolver(stack, project.values, primaryTarget));
    return resolvers.get(stack.name);
  };
  const sub = (stack, text, ctx) =>
    substitute(String(text ?? ''), resolverFor(stack), stack.declared, errors, ctx, NO_PATTERNS).trim();

  const commands = [];
  const agents = [];
  for (const { stack, kind, item } of selection.items) {
    if (kind === 'skills') {
      const { data } = parseFrontmatter(fs.readFileSync(path.join(item.dir, 'SKILL.md'), 'utf8'));
      if (!isUserInvocable(data)) continue;
      commands.push({
        name: data.name ?? item.name,
        argumentHint:
          data['argument-hint'] != null
            ? sub(stack, data['argument-hint'], `waffledocs:skills/${item.name}#argument-hint`)
            : '',
        description: sub(stack, data.description, `waffledocs:skills/${item.name}#description`),
      });
    } else if (kind === 'agents') {
      agents.push({
        name: item.data.name ?? item.name,
        description: sub(stack, item.data.description, `waffledocs:agents/${item.name}#description`),
        skills: Array.isArray(item.data.skills) ? item.data.skills : [],
      });
    }
  }
  // Alphabetical, so output is deterministic (stable lock hash) regardless of stack order.
  commands.sort((a, b) => a.name.localeCompare(b.name));
  agents.sort((a, b) => a.name.localeCompare(b.name));

  const docs = [];
  if (commands.length) {
    docs.push({ rel: CHEATSHEET_MD, content: cheatsheetMarkdown(commands, toolkit.name) });
    docs.push({ rel: CHEATSHEET_SVG, content: cheatsheetSvg(commands, toolkit.name) });
  }
  if (agents.length) {
    docs.push({ rel: TEAM_MD, content: teamMarkdown(agents, toolkit.name) });
    docs.push({ rel: TEAM_SVG, content: teamSvg(agents, toolkit.name) });
  }
  return docs;
}

const GENERATED_BANNER =
  '<!-- Generated by `wafflestack render` from the installed selection — do not edit; re-render to update. -->';

/** Collapse whitespace, take the first sentence, cap length at a word boundary with `…`. */
function oneLiner(text, maxLen) {
  const flat = String(text).replace(/\s+/g, ' ').trim();
  let s = flat;
  const m = /^(.*?[.!?])(\s|$)/.exec(flat);
  if (m && m[1].length >= 24) s = m[1];
  if (s.length > maxLen) {
    s = `${s.slice(0, maxLen - 1).replace(/\s+\S*$/, '').trimEnd()}…`;
  }
  return s;
}

function cheatsheetMarkdown(commands, toolkitName) {
  const lines = [
    GENERATED_BANNER,
    '',
    '# Skills cheat sheet',
    '',
    `Slash commands available in this repo, assembled from the installed **${toolkitName}** skills.`,
    'Type `/<name>` in your agent to run one. Regenerated on every `wafflestack render`.',
    '',
  ];
  for (const c of commands) {
    const hint = c.argumentHint ? ` \`${c.argumentHint.replace(/`/g, '')}\`` : '';
    lines.push(`- **\`/${c.name}\`**${hint} — ${oneLiner(c.description, 200)}`);
  }
  lines.push('', `_${commands.length} command${commands.length === 1 ? '' : 's'} · generated — do not edit._`, '');
  return lines.join('\n');
}

function teamMarkdown(agents, toolkitName) {
  const lines = [
    GENERATED_BANNER,
    '',
    '# Team',
    '',
    `Specialist agents installed in this repo, assembled from the **${toolkitName}** selection.`,
    "Delegate to one by name (via the Task tool or your harness's subagent mechanism). Each agent",
    'lists the skills it is granted — its hand-off points. Regenerated on every `wafflestack render`.',
    '',
  ];
  for (const a of agents) {
    lines.push(`## \`${a.name}\``, '', a.description);
    if (a.skills.length) {
      lines.push('', `**Skills / hand-offs:** ${a.skills.map((s) => `\`${s}\``).join(', ')}`);
    }
    lines.push('');
  }
  lines.push(`_${agents.length} agent${agents.length === 1 ? '' : 's'} · generated — do not edit._`, '');
  return lines.join('\n');
}

// ---- Branded SVG one-pagers (self-contained: no external fonts/images, GitHub-renderable) --

// Palette + type per assets/README.md. System-font fallbacks stand in for the brand fonts,
// which cannot be loaded at GitHub render time — the guardrail explicitly allows this.
const BG = '#1A0D03';
const GOLDEN = '#F5C752';
const SYRUP = '#F08A1D';
const CREAM = '#FFF3DC';
const MUTED = '#C9A87C';
const RULE = '#5C4630';
const DISPLAY = "'Baloo 2', 'Trebuchet MS', system-ui, sans-serif";
const BODY = "'Outfit', system-ui, -apple-system, 'Segoe UI', Roboto, sans-serif";
const MONO = "'JetBrains Mono', ui-monospace, 'SFMono-Regular', Menlo, Consolas, monospace";

const W = 880;
const PAD = 40;
const HEADER_H = 132;
const ROW_H = 62;
const ROW_GAP = 26; // between the header rule and the first row
const FOOTER_H = 44;

function esc(s) {
  return String(s).replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&apos;' }[c]));
}

function truncateChars(text, max) {
  const s = String(text);
  if (s.length <= max) return s;
  return `${s.slice(0, max - 1).replace(/\s+\S*$/, '').trimEnd()}…`;
}

// The flat waffle mark (assets/wafflestack-flat.svg), scaled into the header as chrome.
function waffleGlyph(x, y, scale) {
  const pockets = [16.75, 35.5, 54.25]
    .flatMap((px) => [16.75, 35.5, 54.25].map((py) => `<rect x="${px}" y="${py}" width="13" height="13" rx="4.5" fill="#DE8127"/>`))
    .join('');
  return (
    `<g transform="translate(${x},${y}) scale(${scale})" stroke-linejoin="round">` +
    '<rect x="22" y="22" width="70" height="70" rx="18" fill="#D0902B" stroke="#5B2B0E" stroke-width="6"/>' +
    '<rect x="14.5" y="14.5" width="70" height="70" rx="18" fill="#E4A93D" stroke="#5B2B0E" stroke-width="6"/>' +
    '<rect x="7" y="7" width="70" height="70" rx="18" fill="#F5C752" stroke="#5B2B0E" stroke-width="6.5"/>' +
    pockets +
    '</g>'
  );
}

/**
 * Shared frame. `rows` is `[{ primary, secondary }]`:
 *   primary   — the golden mono headline (`/name` or an agent name)
 *   secondary — the cream one-line description
 * Height is derived from the row count, so the layout sizes itself to the item count. The
 * SVG is a visual summary — argument syntax lives in the Markdown cheat sheet, not here.
 */
function svgFrame({ title, eyebrow, rows, footer }) {
  const bodyTop = HEADER_H + ROW_GAP;
  const height = bodyTop + rows.length * ROW_H + FOOTER_H;
  const parts = [
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${W} ${height}" width="${W}" height="${height}" font-family="${BODY}" role="img" aria-label="${esc(title)}">`,
    `<title>${esc(eyebrow)} — ${esc(title)}</title>`,
    `<rect width="${W}" height="${height}" fill="${BG}"/>`,
    waffleGlyph(PAD, 38, 0.5),
    `<text x="112" y="64" font-family="${MONO}" font-size="13" font-weight="700" letter-spacing="3" fill="${SYRUP}">${esc(eyebrow.toUpperCase())}</text>`,
    `<text x="112" y="100" font-family="${DISPLAY}" font-size="30" font-weight="800" fill="${CREAM}">${esc(title)}</text>`,
    `<rect x="${PAD}" y="${HEADER_H - 18}" width="${W - 2 * PAD}" height="3" rx="1.5" fill="${SYRUP}"/>`,
  ];
  rows.forEach((r, i) => {
    const top = bodyTop + i * ROW_H;
    if (i > 0) {
      parts.push(`<line x1="${PAD}" y1="${top - 13}" x2="${W - PAD}" y2="${top - 13}" stroke="${RULE}" stroke-width="1" opacity="0.4"/>`);
    }
    parts.push(
      `<text x="${PAD}" y="${top + 20}" font-family="${MONO}" font-size="17" font-weight="700" fill="${GOLDEN}">${esc(r.primary)}</text>`,
      `<text x="${PAD}" y="${top + 44}" font-size="15" fill="${CREAM}">${esc(truncateChars(r.secondary, 92))}</text>`,
    );
  });
  parts.push(
    `<text x="${PAD}" y="${height - 18}" font-size="12.5" fill="${MUTED}">${esc(footer)}</text>`,
    '</svg>',
  );
  return `${parts.join('\n')}\n`;
}

function cheatsheetSvg(commands, toolkitName) {
  const rows = commands.map((c) => ({
    primary: `/${c.name}`,
    secondary: oneLiner(c.description, 120),
  }));
  return svgFrame({
    title: 'Skills cheat sheet',
    eyebrow: toolkitName,
    rows,
    footer: `${commands.length} command${commands.length === 1 ? '' : 's'} · generated by wafflestack render — do not edit`,
  });
}

function teamSvg(agents, toolkitName) {
  const rows = agents.map((a) => ({
    primary: a.name,
    secondary: oneLiner(a.description, 120),
  }));
  return svgFrame({
    title: 'Team',
    eyebrow: toolkitName,
    rows,
    footer: `${agents.length} agent${agents.length === 1 ? '' : 's'} · generated by wafflestack render — do not edit`,
  });
}
